networks:
  default:
    name: async-trace
    driver: bridge

services:
  parentservice:
    user: root
    container_name: parentservice
    build: ./parent
    restart: unless-stopped
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
      - OTEL_SERVICE_NAME=parentservice
      - PARENT_SERVICE_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      jaeger:
        condition: service_started

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: jaeger
    command:
    restart: unless-stopped
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
      - "14268:14268"