---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: parent-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-parent-sa
rules:
  - apiGroups: [""]
    resources: [pods, pods/exec]
    verbs: [create, get, list, watch, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-parent-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-parent-sa
subjects:
  - kind: ServiceAccount
    name: parent-sa
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parent-deployment
  labels:
    app: parent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parent
  template:
    metadata:
      labels:
        app: parent
    spec:
      serviceAccountName: parent-sa
      containers:
        - name: parent
          image: lak9348/parent-process:v1.0.2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: parent-service
spec:
  selector:
    app: parent
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
